services:
  db2:
    container_name: db2
    image: icr.io/db2_community/db2
    privileged: true
    ports:
      - 50000:50000
    environment:
      LICENSE: "accept"
      DB2INSTANCE: "db2inst1"
      DB2INST1_PASSWORD: "password"
      DBNAME: "testdb"
      BLU: "false"
      ENABLE_ORACLE_COMPATIBILITY: "false"
      UPDATEAVAIL: "NO"
      TO_CREATE_SAMPLEDB: "false"
      REPODB: "false"
      IS_OSXFS: "false"
      PERSISTENT_HOME: "false"
      HADR_ENABLED: "false"
      ETCD_ENDPOINT:
      ETCD_USERNAME:
      ETCD_PASSWORD:
    healthcheck:
      test: su - db2inst1 -c "db2 connect to testdb; db2 select 1 from sysibm.sysdummy1" || exit 1
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 10
